### ISSUE TITLE
How i can put -insecure

### ISSUE THREAD

**Issue by MasterWindowS** [Natxo09/CS2Server-Creator#1]
This tool is very useful, thank you very much for creating it. I wanted to see if I could test custom maps and apparently I have to use the -insecure, how do I use it with this?

**Comment by Natxo09** [comment]
> This tool is very useful, thank you very much for creating it. I wanted to see if I could test custom maps and apparently I have to use the -insecure, how do I use it with this?

I was doing it yesterday but it got late. This afternoon, you'll have the update with the option to add -insecure. Since you mentioned the workshop maps, I'll add a section to include custom startup arguments so you can add -map {workshopMapName}.

**Comment by Natxo09** [comment]
I've uploaded the new version. I haven't been able to test it on the CS2 servers with the Workshop maps, but in theory, you should be able to run it. I've added the Custom Parameters option so you can add +map {MapName} for the server to execute it directly. Check the documentation as I've updated it. Thank you!

**Comment by MasterWindowS** [comment]
Thanks you <3
