### ISSUE TITLE
Custom port is not working

### ISSUE THREAD

**Issue by dvgmdvgm** [Natxo09/CS2Server-Creator#4]
Hello. By default your app is using 27015 port but on my router is opened another port. Even if i try to type my opened port into your app server is running with default 27015 port.

**Comment by Natxo09** [comment]
> Hello. By default your app is using 27015 port but on my router is opened another port. Even if i try to type my opened port into your app server is running with default 27015 port.

I'll check if they have changed anything, I'll look at it today and upload a new version, give me a few hours.

**Comment by Natxo09** [comment]
> Hello. By default your app is using 27015 port but on my router is opened another port. Even if i try to type my opened port into your app server is running with default 27015 port.

Hi, the new version with the bug fixed has been uploaded, it's version 1.2.1. If you encounter any more issues, please don't hesitate to report them, and thank you very much for using the application and taking the time to report the bug :)
