### ISSUE TITLE
public ip problem

### ISSUE THREAD

**Issue by csoyuncu** [Natxo09/CS2Server-Creator#7]
I have server system with cs 1.6 and cs2 servers. However, when I want to start the CS2 server via public IP: 27015, I constantly get the port in use error. But that ip and port are idle... how can I solve this?

**Comment by Natxo09** [comment]
Hi, sorry for the delayed response. Does the error only occur when you open it with the application, or do you also get the error when opening it manually? In any case, you could check if that port is being used by any of your processes with:
`sudo lsof -i :27015` on Linux and 
`netstat -aon | findstr :27015` on Windows.
